name = "FlockingAnalysis"
uuid = "06962e27-4ff1-49f9-874f-af87d05cc986"
authors = ["ardy-monaghan <ross.monaghan99@gmail.com>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
ImageBinarization = "cbc4b850-ae4b-5111-9e64-df94c024a13d"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"

[compat]
CairoMakie = "0.15.8"
Contour = "0.6.3"
ImageBinarization = "0.3.1"
ImageFiltering = "0.7.12"
Revise = "3.13.2"
VideoIO = "1.4.0"
